# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrFace' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DrFace

pod 'ProjectOxfordFace'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'MBProgressHUD'
pod 'SCLAlertView'

end
